refactor: add musl-dev to build stage due to
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.

Signed-off-by: sj <sebastianthegreatful@gmail.com>